### ISSUE TITLE
Loot chest

### ISSUE THREAD

**Issue by Pligzy88** [Funwayguy/StandardQuestingPack#102]
I am playing the Engineer's life pack and i got a loot chest from a quest but when i opened the loot chest i just got  NULL text and an alert to alt + i which gave me this    https://paste.dimdev.org/ofuqajuyen.mccrash

**Comment by Minsc007** [comment]
Same Issue.

https://paste.dimdev.org/buqunacafi.mccrash

**Comment by Funwayguy** [comment]
NULL is when no loot has been setup. It used to default to dungeon loot but this was exploited in some packs to break progression due to unintended items. Now pack devs must specifically say if they intend to roll that loot instead of relying on fallback measures.

The crash has already bern fixed in Standard Expansion 3.4.172.

**Comment by Pligzy88** [comment]
So there is no fix ...I just have to stop playing the modpack.....nice

**Comment by Funwayguy** [comment]
The crash HAS been fixed. NULL means the _pack dev_ needs to go set it up properly from now on.

**Comment by Pligzy88** [comment]
That's where my issue is....He said it is fixed lol

Robert Nathan Plant

**Comment by Minsc007** [comment]
OK, so I am to direct this issue to the modpack author.  Thanks for the reply.

**Comment by Pligzy88** [comment]
> OK, so I am to direct this issue to the modpack author. Thanks for the reply.

I've already done this ..He said it's a mod issue not the pack itself....Round in circles...
