### ISSUE TITLE
Can't Open Loot Chests

### ISSUE THREAD

**Issue by MCJediYoda** [Funwayguy/StandardQuestingPack#37]
I am using version 2.3.116 and when I right click any of the loot chests nothing happens.  I have no problems with version 1.3.92.  I am using a custom theme but I wouldn't think that would have broken it?

Forge 1.10.2 - 12.18.3.2185

Thanks

MCJediYoda

**Comment by SDUBZ** [comment]
i am also having the same issue too

**Comment by SDUBZ** [comment]
i believe that the default loot wasnt generating,because i noticed the default loot file once deleted didnt regen itself

**Comment by Funwayguy** [comment]
@SDUBZ It's not supposed to regen. That file is specified by the pack developer. Deleting it would render all words devoid of pack defined loot.

The chests should however should still open with dungeon loot if no custom loot is defined. I'm yet to actually recreate this issue which is why I haven't sent out a fix for it yet.

**Comment by SDUBZ** [comment]
@Funwayguy  I cant even edit loot chest either even with version StandardExpansion-2.3.118 in fact no loot chest open still

also noticed this appear in console not sure if triggered when opening chest or just wierdness going on in world 
[what.txt](https://github.com/Funwayguy/StandardQuestingPack/files/679564/what.txt)

**Comment by SDUBZ** [comment]
funny this issue only happend after i updated to 2.3 versions of bqm and its addons

**Comment by Funwayguy** [comment]
I'm able to recreate this issue now that I updated the API implementation so hopefully a fix isn't too far off now.

@SDUBZ That's probably because I rewrote most of the mod from the ground up in 2.x.x. It's muuuuch nicer to work with for me and other developers compared to before. Plus I can add more features and fix things faster now
