### ISSUE TITLE
[1.12.2] Cannot select BabyMobs mob

### ISSUE THREAD

**Issue by Insane96** [Funwayguy/StandardQuestingPack#58]
I'm creating quests. As an hunt task, there's no way to select a BabyMob, the mod always resets to Zombie

Found out that adding them manually works.

**Comment by Funwayguy** [comment]
I know this is a pretty old issue by now but baby mods are defined by a single NBT tag. They aren't separate entities from the adults and that's why there's no distinction between them in the selection screen. Just select the adult you want and toggle `isBaby` in the tags to get the desired baby subtype.
