### ISSUE TITLE
BUG: All Command rewards and some quests Broken in new update

### ISSUE THREAD

**Issue by SirAron111** [Funwayguy/StandardQuestingPack#88]
Now that I updated all command quests don’t work at all anymore. Also it seems that the rewards are broken as well I have for example right in the first quest 3 items that I should get but instead I only get the first one.
BetterQuesting-3.5.299.jar 
StandardExpansion-3.4.157.jar 

Upgraded command rewards to run as a functions (allows for multi-line scripts too)
And how exactly does that work now???? Before I had things like /gamerule doFireTick false
Or First reward being /#import RitualTest2 -x -8 -y 198 -z -8 …. Second reward being /#confirm
And they all don’t work anymore the first was in the first quest turning fire ticks to false the other 2 where in the same quest as a reward one after the other making a structure spawn but now nothing works anymore do I have to rewrite them how do I use the command rewards running as functions?????

Also i can now claim rewards infinitly

**Comment by SirAron111** [comment]
Also "Command reward display is much more customisable" the reward doesn’t get displayed at all anymore there is no more text showing only a function to toggle the icon of the block to be visible

**Comment by SirAron111** [comment]
https://pastebin.com/m6kRyfDq hope that helps

**Comment by Funwayguy** [comment]
I couldn't find an immediate issue with the command reward but did notice something. Do the import and confirm commands actually use a `#` symbol?

**Comment by SirAron111** [comment]
Yes they need it its Recurrent Complex Commands to spawn structure but they aren’t the only problem even the do fire tick one doesn’t trigger anymore and that just has a normal /

**Comment by SirAron111** [comment]
They all also don’t even display next to the Command block symbol anymore like before.
If you want to see it try downloading my pack Dimension Zero and open the Edit mode with the new versions of your mods the command quests are the very first one and the ones in the ???? quest line. Shouldn’t take too long
Hope that helps

**Comment by Funwayguy** [comment]
I'll double check the doFireTick command but I'll have to talk to the RC dev about those other ones. You can't use preceeding hashes in a vanilla mcfunction script because they get interpreted as comments. I don't enforce this rule, vanilla does. This makes RC unusable in such scripts and therefore in the new command rewards.

*sigh*

Honestly I think it would be easier to downgrade SE until this can be sorted out on both ends.

**Comment by Funwayguy** [comment]
The text was replaced by an editable description field because I had complaints that devs couldn't either completely hide the generic text or have a more descriptive display for the reward. This way you can either leave it blank or type whatever you want.

**Comment by SirAron111** [comment]
Thx for the effort XD I am working …... and plan to work even more with the command quests especially in combination with the RC mod to spawn structures for quests as this is pretty nice like go to x location interact with x and bam dungeon or bam you are in a labyrinth XD. So I hope it will be easy to fix. Feel free to mess around with my pack to find the error the quests are already set up to and work fine in the previous version. Hope it helps you find a way around it. And on a side note you really need to enhance your wiki for the mod for idiots like me its really hard to know what to do where and how a few more pictures explaining certa9in things would be nice. Like how the new command as scripts should be written to work or what that means if you don’t have programming knowledge like me it’s hard to get by sry for not understanding it.

**Comment by Funwayguy** [comment]
Just double checked and `/gamerule doFireTick false` appears to function just fine in a command reward. Recurrent Complex also has a config to change the command prefix so that should solve the other issue (seems odd they even need one). I have reported the potential issue of their defaults to the dev regardless though: https://github.com/Ivorforce/RecurrentComplex/issues/390

I haven't really touched the wiki in a long while and probably won't until the the whole GUI layout is replaced. That way I don't end up having to rewrite it twice. The function script syntax however is a vanilla thing and some information on it can be found [here](https://minecraft.gamepedia.com/Function_(Java_Edition))

**Comment by SirAron111** [comment]
Setting it to another symbol works like “!” or anything else in the config and than replacing the command works. Thx for the help.

On another note would it be possible to add a JEI integration to the quest books task? Crafting and retrieval mostly so that people can click on the icon of the item in the Questbook and jei opens up with that items recipe? I better make a separate page for this as an enhancement.
